# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0004_auto_20160726_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.PositiveSmallIntegerField()),
                ('players', models.ManyToManyField(to='poker_api.Player')),
            ],
        ),
    ]
