# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0005_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poker_api.Table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='pot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
