# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0006_auto_20160726_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poker_api.Player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poker_api.Table'),
        ),
    ]
